### PR TITLE
Fix empty file crash

### LINKED ISSUE #147: crash on engine download in flatpak
Happens only in flatpak image but every time. Many people must have faced this problem... 
Steps to reproduce: Rightclick on the server, select download engine 1.0.5.0. Crashes on unpacking because one of the files namely springsettings.cfg has zero size.
I debugged to find out that outSizeProcessed variable is zero and CSevenZipArchive::GetFile crashes because of it.

```
/usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::reference = unsigned char&; std::          vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.                                


#0  0x00007ffff66497f5 in raise () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6632855 in abort () at /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x0000555555ae08e8 in std::__replacement_assert(char const*, int, char const*, char const*) (__file=__file@entry=0x5555562b1250 "/usr/include/ c++/10.2.0/bits/stl_vector.h", __line=__line@entry=1045, __function=__function@entry=0x555556393eb0 "std::vector<_Tp, _Alloc>::reference std::     vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::      vector<_Tp, _Alloc"..., __condition=__condition@entry=0x5555562b10c0 "__builtin_expect(__n < this->size(), true)") at /usr/include/c++/10.2.0/     x86_64-unknown-linux-gnu/bits/c++config.h:457
#3  0x000055555629814f in std::vector<unsigned char, std::allocator<unsigned char> >::operator[](unsigned long) (__n=0, this=0x7ffff2b65150) at /  usr/include/c++/10.2.0/bits/stl_vector.h:1792
#4  CSevenZipArchive::GetFile(unsigned int, std::vector<unsigned char, std::allocator<unsigned char> >&) (this=0x7fffe43df1e0, fid=<optimized      out>, buffer=std::vector of length 0, capacity 0) at src/downloader/lib/src/FileSystem/SevenZipArchive.cpp:207
#5  0x0000555556291ae6 in CFileSystem::extract(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::       __cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) (this=<optimized out>, filename="/home/tommy/.spring/     engine/spring_105.0_minimal-portable-linux64-static.7z", dstdir="/home/tommy/.spring/engine/linux64/105.0", overwrite=false) at src/downloader/lib/src/FileSystem/FileSystem.cpp:530
#6  0x0000555556293906 in CFileSystem::extractEngine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std:: __cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::  allocator<char> > const&) (this=this@entry=0x5555578f3ed0, filename="/home/tommy/.spring/engine/spring_105.0_minimal-portable-linux64-static.7z",  version="105.0", platform="linux64") at src/downloader/lib/src/FileSystem/FileSystem.cpp:489
#7  0x0000555555e7968b in download_engine(std::__cxx11::list<IDownload*, std::allocator<IDownload*> >&) (dllist=...) at /usr/include/c++/10.2.0/   bits/char_traits.h:322
#8  0x0000555555e7a99f in DownloadStart() () at src/downloader/lib/src/pr-downloader.cpp:280
#9  0x0000555555d4b1b0 in DownloadItem::Run() (this=0x555557871890) at src/downloader/prdownloader.cpp:101
#10 0x0000555555de7529 in LSL::WorkItemQueue::Process() (this=0x5555578cf2e8) at src/downloader/lib/src/lsl/lslutils/thread.cpp:124
#11 0x00007ffff6a25a74 in execute_native_thread_routine () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007ffff6cb54d2 in start_thread () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
#13 0x00007ffff670e323 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6
```

Nothing interesting in logs.
```
2022-05-11 19:55:19.1652291 Info    ystem/FileSystem.cpp:188  Using filesystem-writepath: /home/tommy/.spring
2022-05-11 19:55:19.1652291 Info    rc/pr-downloader.cpp:177  Free disk space: 330138 MB
2022-05-11 19:55:19.1652291 Info    ader/CurlWrapper.cpp:62   libcurl 7.71.1-DEV GnuTLS/3.7.2 (NSS/3.68.1) (OpenSSL/1.1.1n)
2022-05-11 19:55:19.1652291 Info    ader/CurlWrapper.cpp:42   SSL backend #0: 'gnutls' (ID: 2)
2022-05-11 19:55:19.1652291 Info    ader/CurlWrapper.cpp:42   SSL backend #1: 'nss' (ID: 3)
2022-05-11 19:55:19.1652291 Warning ader/CurlWrapper.cpp:46   Multiple SSL backends, this will very likely fail!
2022-05-11 19:55:19.1652291 Info    ader/CurlWrapper.cpp:42   SSL backend #2: 'openssl' (ID: 1)
2022-05-11 19:55:19.1652291 Warning ader/CurlWrapper.cpp:46   Multiple SSL backends, this will very likely fail!
2022-05-11 19:55:19.1652291 Info    der/prdownloader.cpp:56   Starting download of filename: , name: spring 105.0, category: engine
2022-05-11 19:55:19.1652291 Info    /RapidDownloader.cpp:135  setOption forceupdate = 
2022-05-11 19:55:20.1652291 Info    p/HttpDownloader.cpp:287  md5 correct: 843c450efee82108aa68d9551dff1f17
2022-05-11 19:55:20.1652291 Info    ystem/FileSystem.cpp:510  Extracting /home/tommy/.spring/engine/spring_105.0_minimal-portable-linux64-static.  7z to /home/tommy/.spring/engine/linux64/105.
```

### PR DESCRIPTION
**Pull request by dzosz**
fixes #147 
I spent few mins testing downloading everything that is available. seems fine

### CODE REVIEW

File: src/FileSystem/FileSystem.cpp [hunk 1]
```diff
@@ -559,13 +560,11 @@ bool CFileSystem::extract(const std::string& filename,
 			delete archive;
 			return false;
 		}
-		int res = 1;
-		if (!buf.empty())
-			res = fwrite(&buf[0], buf.size(), 1, f);
+		size_t written = fwrite(buf.data(), 1, buf.size(), f); // might create empty file
```
Comment (dzosz) [inline src/FileSystem/FileSystem.cpp:563]: instead of 1 should be 
`sizeof(decltype(buf)::value_type);`
but I don't think we have c++11?

Comment (dzosz) [inline src/FileSystem/FileSystem.cpp:563]: instead of 1 should be 
`sizeof(decltype(buf)::value_type);`
but I don't think we have c++11?

File: src/FileSystem/SevenZipArchive.cpp [hunk 2]
```diff
@@ -204,7 +204,7 @@ bool CSevenZipArchive::GetFile(unsigned int fid,
 			     &allocImp, &allocTempImp);
 	if (res == SZ_OK) {
 		buffer.resize(outSizeProcessed);
-		memcpy(&buffer[0], (char*)outBuffer + offset, outSizeProcessed);
+		memcpy(buffer.data(), (char*)outBuffer + offset, outSizeProcessed);
```
Comment (dzosz) [inline src/FileSystem/SevenZipArchive.cpp:207]: instead checking for emptiness we take invalid pointer and assume memcpy will do nothing with it

**Comment by abma** [comment]
thank you!
