### PR TITLE
Fix #145 (unicode file paths)

### LINKED ISSUE #145: CFileSystem::getMBsFree seems to fail when the path contains non-ASCII characters
# Overview

I think the Windows block of [CFileSystem::getMBsFree](https://github.com/spring/pr-downloader/blob/master/src/FileSystem/FileSystem.cpp#L644-L650) should use `GetDiskFreeSpaceExW` [here](https://github.com/spring/pr-downloader/blob/master/src/FileSystem/FileSystem.cpp#L645) instead of `GetDiskFreeSpaceEx` to support Unicode paths.

# Details

A user reported his friend having issue getting BAR to work, with the following showing error message (full logs in Reference 1):

```
Error getting free disk space on C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data: 3
Couldn't open C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data\rapid\repos.springrts.com\repos.gz.tmp: No such file or directory
```

The user confirmed they have enough disk space. Based on the non-ASCII characters in the logs, I suspected this is actually related to finding the path rather than disk space (which in fact obvious since the next error complains a file/directory couldn't be found). The user, who, unlike his friend, has the game working, tried to install the game on a path that does have non-ASCII characters, and that broke the game for him, with similar logs (see Reference 2). 

# Reference

1. Log from the original issue (the user's friend):

```
Sun Apr 10 2022 15:50:11 GMT+0200 (czas środkowoeuropejski letni) warn] [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:647:getMBsFree():Error getting free disk space on C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data: 3
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:45:propen():Couldn't open C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data\rapid\repos.springrts.com\repos.gz.tmp: No such file or directory
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/File.cpp:83:Open():open(C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data\rapid\repos.springrts.com\repos.gz): No such file or directory
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:81:DownloadUrl():Error in curl SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - Funkcja obs�ugi odwo�a� nie mo�e sprawdzi� odwo�ania, poniewa� serwer odwo�a� jest w trybie offline.)
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:196:search():Error downloading https://springfiles.springrts.com/json.php?category=game&springname=byar:test 
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:647:getMBsFree():Error getting free disk space on C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data: 3
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/pr-downloader.cpp:266:DownloadStart():Insuffcient free disk space (0 MiB) on C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data: 1024 MiB needed
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 5

[Sun Apr 10 2022 15:50:11 GMT+0200 (czas środkowoeuropejski letni) error] byar:test: [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:647:getMBsFree():Error getting free disk space on C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data: 3
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:45:propen():Couldn't open C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data\rapid\repos.springrts.com\repos.gz.tmp: No such file or directory
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/File.cpp:83:Open():open(C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data\rapid\repos.springrts.com\repos.gz): No such file or directory
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:81:DownloadUrl():Error in curl SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - Funkcja obs�ugi odwo�a� nie mo�e sprawdzi� odwo�ania, poniewa� serwer odwo�a� jest w trybie offline.)
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:196:search():Error downloading https://springfiles.springrts.com/json.php?category=game&springname=byar:test 
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:647:getMBsFree():Error getting free disk space on C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data: 3
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/pr-downloader.cpp:266:DownloadStart():Insuffcient free disk space (0 MiB) on C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data: 1024 MiB needed
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 5

[Sun Apr 10 2022 15:50:11 GMT+0200 (czas środkowoeuropejski letni) info] [Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:188:setWritePath():Using filesystem-writepath: C:\Users\Otu�\AppData\Local\Programs\Beyond-All-Reason\data
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/pr-downloader.cpp:178:DownloadSetConfig():Free disk space: 0 MB
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:62:DumpVersion():libcurl 7.64.0 Schannel
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:42:GetTLSBackend():SSL backend #0: 'schannel' (ID: 8)
```

2. Log from trying to intentionally using 

```
[Sun Apr 10 2022 23:23:38 GMT+0200 (czas środkowoeuropejski letni) info] Download started: byar:test

[Sun Apr 10 2022 23:23:38 GMT+0200 (czas środkowoeuropejski letni) info] pr-downloader 0.7-603-g31a5070 (windows64)

[Sun Apr 10 2022 23:23:39 GMT+0200 (czas środkowoeuropejski letni) warn] [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:647:getMBsFree():Error getting free disk space on C:\Program Files\�iwinski\Beyond-All-Reason\data: 3
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:45:propen():Couldn't open C:\Program Files\�iwinski\Beyond-All-Reason\data\rapid\repos.springrts.com\repos.gz.tmp: No such file or directory
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/File.cpp:83:Open():open(C:\Program Files\�iwinski\Beyond-All-Reason\data\rapid\repos.springrts.com\repos.gz): No such file or directory
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:647:getMBsFree():Error getting free disk space on C:\Program Files\�iwinski\Beyond-All-Reason\data: 3
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/pr-downloader.cpp:266:DownloadStart():Insuffcient free disk space (0 MiB) on C:\Program Files\�iwinski\Beyond-All-Reason\data: 1024 MiB needed
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 5

[Sun Apr 10 2022 23:23:39 GMT+0200 (czas środkowoeuropejski letni) error] byar:test: [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:647:getMBsFree():Error getting free disk space on C:\Program Files\�iwinski\Beyond-All-Reason\data: 3
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:45:propen():Couldn't open C:\Program Files\�iwinski\Beyond-All-Reason\data\rapid\repos.springrts.com\repos.gz.tmp: No such file or directory
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/File.cpp:83:Open():open(C:\Program Files\�iwinski\Beyond-All-Reason\data\rapid\repos.springrts.com\repos.gz): No such file or directory
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:647:getMBsFree():Error getting free disk space on C:\Program Files\�iwinski\Beyond-All-Reason\data: 3
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/pr-downloader.cpp:266:DownloadStart():Insuffcient free disk space (0 MiB) on C:\Program Files\�iwinski\Beyond-All-Reason\data: 1024 MiB needed
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 5

[Sun Apr 10 2022 23:23:39 GMT+0200 (czas środkowoeuropejski letni) info] [Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:188:setWritePath():Using filesystem-writepath: C:\Program Files\�iwinski\Beyond-All-Reason\data
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/pr-downloader.cpp:178:DownloadSetConfig():Free disk space: 0 MB
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:62:DumpVersion():libcurl 7.64.0 Schannel
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:42:GetTLSBackend():SSL backend #0: 'schannel' (ID: 8)
```

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

File: src/FileSystem/FileSystem.cpp [hunk 1]
```diff
@@ -642,7 +642,7 @@ unsigned long CFileSystem::getMBsFree(const std::string& path)
 {
 #ifdef _WIN32
 	ULARGE_INTEGER freespace;
-	BOOL res = GetDiskFreeSpaceEx(s2ws(path).c_str(), &freespace, nullptr, nullptr);
+	BOOL res = GetDiskFreeSpaceExW(s2ws(path).c_str(), &freespace, nullptr, nullptr);
```
Comment (rafidka) [inline src/FileSystem/FileSystem.cpp:645]: Is this sufficient? I assume, based on the name, that `s2ws` converts a string to a wide-string, so it should be sufficient, but just double checking.

**Comment by abma** [comment]
thank you!
